version: 1
applications:
  - appRoot: webapp
    frontend:
      phases:
        preBuild:
          commands:
            - npm ci --legacy-peer-deps
        build:
          commands:
            - cp .env.local.example .env.local
            - npm run build
            - cp -r .next/standalone/webapp/. .next/standalone-output/
            - cp -r .next/static .next/standalone-output/.next/
            - cp -r public .next/standalone-output/
      artifacts:
        baseDirectory: .next/standalone-output
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
          - .next/cache/**/*